# Setup
setup: pretext

# Model
backbone: resnet_ts
model_kwargs:
   head: mlp
   features_dim: 128  # Output feature dimension for the head

transformer_kwargs:
   in_channels: 55
   seq_len: 200
   embed_dim: 8
   num_heads: 2
   num_layers: 2

res_kwargs:
   in_channels: 55
   mid_channels: 4
   dropout_p: 0.1


# Dataset
train_db_name: MSL
val_db_name: MSL
num_classes: 10

# Loss
criterion: pretext
criterion_kwargs:
   temperature: 0.4

# Hyperparameters
epochs: 30
optimizer: adam
optimizer_kwargs:
   #nesterov: False
   #momentum: 0.9
   lr: 0.001
   weight_decay: 0.00001
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.01
batch_size: 100
num_workers: 1

# Transformations
augmentation_strategy: ts
transformation_kwargs:
   noise_sigma: 0.01

anomaly_kwargs:
   portion: 0.99
